### ISSUE TITLE
ERROR running npm run build && cordova run browser

### ISSUE THREAD

**Issue by malutanpetronel** [uidb-dev/react.cordova#38]
npm run build && cordova run browser

```
> reco checkversion && react-scripts build && reco copy && cordova build

/usr/local/lib/node_modules/react.cordova/bin/reco2/index.js:437
                newVersion = dataView?.latest[dataView?.versions?.length - 1];

SyntaxError: Unexpected token '.'
    at Object.compileFunction (vm.js:379:18)
    at Generator.next (<anonymous>)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

```

Any idee what happened ?
Last week it worked!

**Comment by malutanpetronel** [comment]
However running 
` npm install -g --save "git://git@github.com:uidb-dev/react.cordova.git#8b7ac36"`
fixes the issue, but, of course will keep reco at an older version on my system
